Very WIP attempt to override proposal card footer
liquidvotingio/decidim-module-liquidvoting pull request #106
Opened 2021-04-23 15:18 UTC by jinjagit

2021-04-26 13:16 UTC, jinjagit commented on lib/decidim/liquidvoting/engine.rb
> +      end
Adding this initializer was key to this change. Note that we need to prepend the cell path, rather than append, to ensure the override of file `app/cells/decidim/proposals/proposal_m/footer.erb` is applied. Thanks, @davefrey, for realizing this!

2021-04-27 11:06 UTC, jinjagit commented
Screenshot of proposals index view ('Amendment' cards, which may also be shown in the proposals index view, and the process show view, never show the 'View Proposal' button, and this is also the case in the original Decidim (non-liquidvoting) version:

![proposals_index](https://user-images.githubusercontent.com/3944042/116231518-e53af280-a750-11eb-8c0d-87c9b26d606a.png)

2021-04-27 13:15 UTC, davefrey reviewed
This looks great! and congrats for getting that footer sorted 💪.

Some general PR comments: coming to the PR I looked first for the issue number (what I read first in a PR)...something like "Resolves #104" in the PR description is ideal if it's known when the PR is created. 

Second, if I can have a visual clue to the changes, like a before and after screenshot of a card, that dials me into the PR quickly.

Other than the minor comments inline to the changes, this looks good to me.

2021-04-27 13:29 UTC, davefrey requested changes

2021-04-27 13:29 UTC, davefrey commented on spec/system/view_proposal_from_index.rb
> +describe "View a Proposal by clicking 'view proposal' on index view proposal card", type: :system do
Looking more closely...I think this spec subtly misses the point of the issue/PR: we want to override presenting the Support button, because we don't yet have a good LV UI for doing that from the Proposals list page. Instead, we want to replace the voting stuff with a View button.

I think a better spec approach is to split the current one (which actually asserts our intention in the _setup_ for testing the View button, which is secondary):
```ruby
describe "Viewing the Proposals list"
  it "replaces the voting footer on the proposal card with a View Proposal button"
  it "goes to the Proposal page when clicking View"
```
We are asserting differences from core Decidim.

2021-04-27 13:31 UTC, jinjagit commented
@davefrey 

> Some general PR comments: coming to the PR I looked first for the issue number (what I read first in a PR)...something like "Resolves #104" in the PR description is ideal if it's known when the PR is created.

Done.

> Second, if I can have a visual clue to the changes, like a before and after screenshot of a card, that dials me into the PR quickly.

Good idea. But... do you have an image of the proposal card _before_ the change? I didn't think to capture one.

2021-04-27 13:32 UTC, jinjagit commented on spec/system/view_proposal_from_index.rb
> +describe "View a Proposal by clicking 'view proposal' on index view proposal card", type: :system do
Makes sense. I'll work on this now.

2021-04-27 13:40 UTC, davefrey commented
I added the before/after images to the description (you can also always get back to "before" by checking out master, or eventually by running the app from a decidim v0.24.0 workspace).

But now that I see the images ... why did we remove the support counts? It seems to add value without adding confusion, and since we override the footer we can do what we want.

2021-04-27 13:44 UTC, jinjagit commented
@davefrey 
> But now that I see the images ... why did we remove the support counts? It seems to add value without adding confusion, and since we override the footer we can do what we want.

I chose to remove them, as they are not show in the process overview page, which presents a selection of proposal cards for the process, with the same 'View Proposal' button on the card footers. Thus, I felt it would be less jarring to the user.

Also, I would need to confirm the count is correct in all cases in this index view (including when we have used our API in various ways to alter it), unless you are already sure of this. I also side-stepped this work by not including the count.

2021-04-27 13:44 UTC, davefrey commented on spec/system/view_proposal_from_index.rb
> +    click_link("View proposal")
(this comment is obsolete; see above about splitting the spec)

2021-04-27 13:46 UTC, davefrey commented
Ah good point about retrieving all the relevant counts, you're exactly right

2021-04-27 13:48 UTC, jinjagit commented
Yes, the fact that they are not included when cards are in other view + have 'View proposal' button gave me a good way to avcoid this issue, for now.  

We can, of course, re-include the count if/when we have the ajax for 'support' button + delegation UI working on the cards (if we wish to do this).

2021-04-27 13:49 UTC, davefrey commented
👍 Consistency with other View Proposal cards, I agree

2021-04-27 14:44 UTC, jinjagit commented on spec/system/view_proposal_from_index.rb
> +describe "View a Proposal by clicking 'view proposal' on index view proposal card", type: :system do
Done.

2021-04-27 14:50 UTC, jinjagit commented
@dave @oliverbarnes I just corrected a one-word typo in a comment, after re-requesting review.

2021-04-27 16:04 UTC, oliverbarnes commented on app/cells/decidim/proposals/proposal_m/footer.erb
> +          <%= t("decidim.proposals.proposals.proposal.view_proposal") %>
Agree - we should only own what we change, it'll be a lot easier to manage and reason about. #91 is related to this

2021-04-27 16:06 UTC, oliverbarnes commented on lib/decidim/liquidvoting/engine.rb
> +        Cell::ViewModel.view_paths.unshift File.expand_path("#{Decidim::Liquidvoting::Engine.root}/app/views") # for partials
yup, YAGNI

2021-04-27 16:17 UTC, oliverbarnes requested changes
Looking great. I agree with most of Dave's comments, expect for the `refresh_api` change - see my comment there

2021-04-27 16:17 UTC, oliverbarnes commented on app/overrides/controllers/decidim/proposals/proposals_controller.rb
> +        refresh_from_api(specific_to_a_proposal: false)
🤔  not sure being explicit about this here is useful in any way. `Liquidvoting#user_proposal_state` could be smart about proposal_url being present or not and building state accordingly? 

this way we can have a clean call to `refresh_from_api` each time

2021-04-27 16:17 UTC, davefrey submitted a review, later dismissed

2021-04-27 16:22 UTC, oliverbarnes commented on lib/decidim/liquidvoting/engine.rb
> +        Cell::ViewModel.view_paths.unshift File.expand_path("#{Decidim::Liquidvoting::Engine.root}/app/views") # for partials
would you please remove the second unshift then, @jinjagit?)

2021-04-27 16:23 UTC, jinjagit commented on lib/decidim/liquidvoting/engine.rb
> +        Cell::ViewModel.view_paths.unshift File.expand_path("#{Decidim::Liquidvoting::Engine.root}/app/views") # for partials
Sure. Will do it now.

2021-04-27 16:27 UTC, jinjagit commented on lib/decidim/liquidvoting/engine.rb
> +        Cell::ViewModel.view_paths.unshift File.expand_path("#{Decidim::Liquidvoting::Engine.root}/app/views") # for partials
Done.

2021-04-27 16:30 UTC, jinjagit commented on app/overrides/controllers/decidim/proposals/proposals_controller.rb
> +        refresh_from_api(specific_to_a_proposal: false)
@Dave Any advice/tips on this change - or do you want to do this? I ask because this is the solution you devised to workaround the lack of `proposal_url` for the proposal index view cards.

2021-04-27 16:31 UTC, dave commented on app/overrides/controllers/decidim/proposals/proposals_controller.rb
> +        refresh_from_api(specific_to_a_proposal: false)
Wrong dave 😉

2021-04-27 16:31 UTC, jinjagit commented on app/overrides/controllers/decidim/proposals/proposals_controller.rb
> +        refresh_from_api(specific_to_a_proposal: false)
Oops, sorry!

2021-04-27 17:31 UTC, davefrey commented on app/overrides/controllers/decidim/proposals/proposals_controller.rb
> +        refresh_from_api(specific_to_a_proposal: false)
Just pushed the change, thanks for the improvement! I needed to review because every one of the three `refresh_from_api` methods works slightly differently, to be cleaned up later when we extract that. But it's good to go now.

2021-04-27 17:33 UTC, davefrey approved these changes

2021-04-27 17:33 UTC, oliverbarnes approved these changes

2021-04-27 17:34 UTC, merged