Handle (un)delegation actions asynchronously
liquidvotingio/decidim-module-liquidvoting pull request #37
Opened 2021-02-22 17:18 UTC by davefrey

This is meant to move delegation actions to ajax.

Still fairly broken, main issue is understanding the role of `current_settings` and `current_component`, where things like votes_hidden? or can_participate? are resolved. Unsure when to reference proposals or liquidvoting components

Closes #18

2021-02-22 17:43 UTC, oliverbarnes commented on app/controllers/decidim/liquidvoting/delegations_controller.rb
> +        # @proposal ||= Decidim::Proposals::Proposal.where(component: current_component).find(params[:proposal_id])
Great question for @mrcasals 😄

2021-02-22 17:43 UTC, oliverbarnes commented on app/controllers/decidim/liquidvoting/delegations_controller.rb
> +        # TODO: why do we have to qualify Proposal? is it "isolate_namespace Decidim::Liquidvoting" in engine.rb?
same

2021-02-22 17:45 UTC, oliverbarnes commented on app/views/decidim/liquidvoting/_delegation.html.erb
> +          proposal_id: proposal.id,
Is this working?

2021-02-22 17:46 UTC, oliverbarnes commented on app/views/decidim/liquidvoting/_delegation.html.erb
> +          proposal_id: proposal.id,
as far as submitting the params, at least - replacing the hidden inputs. 

Same question about the ajax request

2021-02-22 17:47 UTC, oliverbarnes commented on app/views/decidim/proposals/proposal_votes/update_buttons_and_counters.js.erb
> +      morphdom($proposalDelegationUI[0], '<%= j(render partial: "decidim/liquidvoting/delegation", locals: { proposal: proposal, from_proposals_list: @from_proposals_list }).strip.html_safe %>');
👍 looking promising. Is it working?

2021-02-23 10:16 UTC, davefrey commented on app/views/decidim/liquidvoting/_delegation.html.erb
> +          proposal_id: proposal.id,
Yes, and yes afaik...the problems are now downstream, when trying to render proposal partials from delegation controller, and missing context like `current_component`

2021-02-23 10:17 UTC, davefrey commented on app/views/decidim/proposals/proposal_votes/update_buttons_and_counters.js.erb
> +      morphdom($proposalDelegationUI[0], '<%= j(render partial: "decidim/liquidvoting/delegation", locals: { proposal: proposal, from_proposals_list: @from_proposals_list }).strip.html_safe %>');
It renders, but that js file is a duplicate, I think we should be reusing the same file

2021-02-23 10:45 UTC, oliverbarnes commented on app/views/decidim/proposals/proposal_votes/update_buttons_and_counters.js.erb
> +      morphdom($proposalDelegationUI[0], '<%= j(render partial: "decidim/liquidvoting/delegation", locals: { proposal: proposal, from_proposals_list: @from_proposals_list }).strip.html_safe %>');
not sure I follow 🤔

2021-02-23 11:16 UTC, davefrey commented on app/views/decidim/proposals/proposal_votes/update_buttons_and_counters.js.erb
> +      morphdom($proposalDelegationUI[0], '<%= j(render partial: "decidim/liquidvoting/delegation", locals: { proposal: proposal, from_proposals_list: @from_proposals_list }).strip.html_safe %>');
sorry... we're past our earlier problems of not finding the `js.erb` etc...and the (un)delegate happens in the api. But post-(un)delegate when we try to render button changes as js, we fail on other normal rails problems in the partials: "vote enabled" helpers etc. Because the user/session/component context is messed up

2021-02-23 11:32 UTC, jinjagit approved these changes
This looks like progress. :+1:

> Still fairly broken, main issue is understanding the role of `current_settings` and `current_component`, where things like votes_hidden? or can_participate? are resolved. Unsure when to reference proposals or liquidvoting components

AFAIK `votes_hidden?` & `can_participate?` are both Decidim concepts, and I imagine, therefore, reference states that are relative to the proposal and/or user involved.

2021-02-23 11:32 UTC, jinjagit commented on app/controllers/decidim/liquidvoting/delegations_controller.rb
> +      # TODO is this used? how is it used? elsewhere we use "proposals" component for db filtering for example
I'm not convinced it is used. Does anything break if it this `current_component` def is commented out?

2021-03-03 16:07 UTC, davefrey commented
Aside from the rubocop problems which I'm doing next, I think this PR meets the objectives of #18 ; it's ready for review/merge from my point of view.

2021-03-04 10:32 UTC, oliverbarnes requested changes
👏👏 great work! Just a few minor requests

2021-03-04 10:32 UTC, oliverbarnes commented on app/controllers/decidim/liquidvoting/proposal_vote_delegations_controller.rb
> +      def lv_state
I think this can be removed since the client call is done explicitly on line 48?

2021-03-04 10:32 UTC, oliverbarnes commented on app/overrides/commands/decidim/proposals/unvote_proposal.rb
>          # TODO: figure out api error approach; currently client raises a RuntimeError
We have an issue for this :)

2021-03-04 10:32 UTC, oliverbarnes commented on app/overrides/commands/decidim/proposals/unvote_proposal.rb
> +        # return broadcast(:invalid, response.errors.messages["votes"].join(", ")) if response.errors.any?
It's ok to remove this commented out code. Once we look into improving the error handling, we'll naturally revisit how it's done in the original proposal component

2021-03-04 10:32 UTC, oliverbarnes commented on app/overrides/commands/decidim/proposals/vote_proposal.rb
> +        # return broadcast(:invalid, response.errors.messages["votes"].join(", ")) if response.errors.any?
Same as with vote proposal, comment can be removed

2021-03-04 10:32 UTC, oliverbarnes commented on app/views/decidim/liquidvoting/_delegation.html.erb
> +  <!-- TODO: send ajax requests instead -->
Can be removed too

2021-03-04 10:32 UTC, oliverbarnes commented on lib/decidim/liquidvoting/engine.rb
> +          # delete generic_delegation_path => "delegations#delete", as: :delegations
Comments not needed here as well :)

2021-03-04 11:32 UTC, davefrey commented on app/controllers/decidim/liquidvoting/delegations_controller.rb
> +        # @proposal ||= Decidim::Proposals::Proposal.where(component: current_component).find(params[:proposal_id])
Deriving the delegations controller on `Decidim::Proposals::ApplicationController`, then following conventions in the sibling `ProposalVotesController`, led us to a clean working set of overrides for proposal, component, etc.

2021-03-05 10:37 UTC, davefrey commented
All feedback is included, PR is clean from my point of view, pending any new comments

2021-03-05 12:13 UTC, oliverbarnes approved these changes

2021-03-05 12:13 UTC, merged