Remove liquidvoting component
liquidvotingio/decidim-module-liquidvoting pull request #40
Opened 2021-02-26 11:48 UTC by davefrey

You will also need to remove the 'liquidvoting' row from the database, or you will get something like:

ActionView::Template::Error (undefined method `decidim_participatory_process_liquidvoting' for #<Decidim::EngineRouter:0x00007facca323d30>

The last segment 'liquidvoting' of that method name is dynamically retrieved from the database,
from decidim_components.manifest_name; changing the value changes the method name lookup.
Removing the row lets things work again.

This seems to leave the code broken in exactly the same ways as before: view rendering fails on
current_settings etc

2021-02-26 16:56 UTC, oliverbarnes requested changes
Now that the code is maturing beyond a spike, it'd be good to remove the commented code and all the TODOs - these are better captured and followed-up on through issues or issue comments.

2021-02-26 16:59 UTC, jinjagit approved these changes
LGTM - but I confess I haven't pulled & tested.

2021-02-26 17:58 UTC, davefrey commented
Definitely I don't like the `TODO`s and I expect most to go away quickly, and I agree issues are better than `TODO`s.

For the moment they're my placeholders as I better understand things; it feels premature to issue-ize them. Give me a few more commits on this PR :-) 

Also it seems I've got some PRs maybe out of order; this PR will be cleaner after #42 and then #39 are merged.

2021-02-26 18:03 UTC, oliverbarnes commented
Hehe, sure! But it sounds like the PR is draft, then?

2021-02-26 18:34 UTC, davefrey commented on app/controllers/decidim/liquidvoting/delegations_controller.rb
> +      def lv_state
I'm pretty confused why this is coming back in, this was added to master some time ago; I must have made a mistake when splitting out the PRs this morning. I confirm this is the right diff now.

2021-02-26 18:35 UTC, davefrey commented
I cleaned things up a bit, the TODOs in particular really belong to other demo work threads. I'll un-draft this.

2021-03-01 10:19 UTC, oliverbarnes approved these changes

2021-03-01 10:19 UTC, merged