Add happy path UAT specs
liquidvotingio/decidim-module-liquidvoting pull request #72
Opened 2021-03-24 11:30 UTC by davefrey

This is to add enough UAT (capybara in spec/system) to have basic coverage of our four main cases: create/remove a vote, create/remove a delegation.

Asserting that the LV api is called correctly for each, but otherwise not testing the api client here.

2021-03-24 13:16 UTC, jinjagit commented
`unsupport_proposal_spec.rb` needs work, as currently relies on clicking Support button to create initial 'supported' state, which means un-supporting is not tested in isolation.

2021-03-24 14:25 UTC, oliverbarnes commented
> `unsupport_proposal_spec.rb` needs work, as currently relies on clicking Support button to create initial 'supported' state, which means un-supporting is not tested in isolation.

It's the only way, since we can't setup state without sending actual requests to the api.

Stubbing in-memory state would defeat the purpose of the acceptance spec, which is to exercise the whole stack and ensure the user-facing feature is fully working

2021-03-24 14:27 UTC, jinjagit commented
> It's the only way, since we can't setup state without sending actual requests to the api.

Yup, that was where I was getting stuck. Thanks. I'll remove the TODO comments then. :+1:

2021-03-24 17:55 UTC, davefrey commented on spec/system/support_delegate_proposal_spec.rb
> +  end
This seemed to be the best of the messy options for tearing down local api data.

We thought also about using the elixir `smoke_test_teardown` from the api repo, but that seemed a more cumbersome dependency than a local script with sql DELETE commands, narrowed to the same org_id used to create the data.

Probably this can be pulled up to a higher level, to execute once before/after the whole rspec run, since users, proposals etc are instantiated per spec.

2021-03-24 18:45 UTC, oliverbarnes commented on spec/system/support_delegate_proposal_spec.rb
> +  end
Interesting, I hadn't thought about the local teardown yet. I see what you mean about the cumbersome dependency: we'd need to run the local api instance as a release, and then do the same eval call that [the CI's k8s teardown does](https://github.com/liquidvotingio/decidim-module-liquidvoting/blob/master/.github/workflows/CI.yml#L75-L91).

The problem with the local script, though, is that it's a second teardown script to maintain. If we change the api's own teardown code at some point, we'll have to remember to update this one.

Maybe we can have a rake task that encapsulates this (and only runs locally), and we can have the cumbersome call in it, so we don't have it run right in the spec (which will get run in the CI as well)? We could have it run after all the specs are run, like it's done in the CI. Given they're each running with different users, I don't expect them to clash...?

2021-03-25 10:37 UTC, davefrey commented on spec/system/support_delegate_proposal_spec.rb
> +  end
I think I like the rake task approach to encapsulate the messiness, esp if it doesn't make the spec cycle time worse ... it's already painful.

For the moment at least I'm going to take the script out of the specs; we can just `teardown ; be rspec` on the command line ourselves. Plus I'm already not clear about the best place to put the :before, :after blocks. And CI !

Separately from how we invoke it, I think it would be simpler, faster, safer for teardown to do the equivalent of `DELETE FROM ... WHERE organization_id = `. The current implementation iterates over every object, and it's also not clear how the `results` table gets cleared; maybe cascading? but then that makes me think about leaks. If we could know the whole org-id space in the database were wiped, it's a win I think. 
Though rake is another slow launch, and the rspec cycle is already pretty long, I'm feeling the pain of iterating.

2021-03-29 13:31 UTC, oliverbarnes commented on spec/system/support_delegate_proposal_spec.rb
> +  end
> For the moment at least I'm going to take the script out of the specs; we can just teardown ; be rspec on the command line ourselves.

Yeah, I've simply been tearing down manually after running specs

> Plus I'm already not clear about the best place to put the :before, :after blocks. And CI !

CI is already taken care of - here's the CI teardown: https://github.com/liquidvotingio/decidim-module-liquidvoting/blob/master/.github/workflows/CI.yml#L75-L91

And here's the release teardown code, to understand what it does: https://github.com/liquidvotingio/api/blob/master/lib/liquid_voting/release.ex#L51-L75

So, I think we don't need to use :before or :after blocks, running the api release teardown once after running specs should be enough, because dynamic factories will ensure there's no leak between tests.

> It's also not clear how the results table gets cleared

This is something that's worth double checking, the api release teardown doesn't touch the voting results data itself.

> I'm feeling the pain of iterating.

🤔  by pain do you mean that, if you don't teardown between specs, you see inconsistent test results due to old factories that weren't cleared up? As said above, I'd expect the factories to not clash (there should be new users, new votes and new delegations in each spec run), because the factories are dynamic and use sequences to generate different data each time.

2021-03-29 13:35 UTC, oliverbarnes commented
See my comments above - in the end I don't think the local teardown is blocking this PR. I'd just remove the local teardown scripts and fix [the rubocop error on the CI](https://github.com/liquidvotingio/decidim-module-liquidvoting/pull/72/checks?check_run_id=2192359765), and open the PR for review

2021-03-29 15:57 UTC, jinjagit commented
I think this might be ready to merge now. Please check!

2021-03-29 16:06 UTC, oliverbarnes requested changes
🙌  looks great! Would you please just remove the teardown script? running `mix ecto:reset` manually on the api accomplishes the same as running the script.

If we choose to have a canonical way of doing this when running specs locally, we can add a rake task later that does the same as the CI, as mentioned in the comments. Not super high priority, though

2021-03-29 16:19 UTC, davefrey commented on spec/system/support_delegate_proposal_spec.rb
> +  end
No, I meant just how damn slow capybara is on my older machines! I can't remember now what triggered teardown, maybe a red herring

2021-03-29 16:20 UTC, merged