Move api mutator calls into liquidvoting module
liquidvotingio/decidim-module-liquidvoting pull request #96
Opened 2021-04-08 18:19 UTC by davefrey

This moves all calls to the four api mutators out of controllers and commands, and into the `Decidim::Liquidvoting` module meant to centralise this kind of thing. So all calls to do Liquidvoting things now look like `Liquidvoting.some_method`, and `ApiClient` is fully wrapped there.

It additionally moves the proposal vote count update into the same wrapper calls, further simplifying the controllers and commands, and insuring that the api call doesn't happen without the vote update (it was not happening for delegations, see below).

The specs for the new methods in `Decidim::Liquidvoting` focus on behavior, not state; no attempt is made to validate api results for example. Instead, we just assert that the new wrapper methods 1) send the appropriate message to `ApiClient` with the correct arguments, and 2) send a `Proposal#proposal_votes_count` message with the expected value.

I tackled this now so that further integration work (endorsements, etc) can copy the new pattern (or whatever new pattern comes out of this review).

Closes #95 

To update the vote count on `create_delegation`, I had to change the api response in the graphql query (now all modifiers return a `voting_result`), and also the api client response (which was systematically returning `true`).

Additionally, the create/destroy delegations were not recording the new vote count in the proposal; that is fixed here.

Resolves #94

2021-04-11 13:25 UTC, oliverbarnes requested changes
Much cleaner and easier to reason about 👏 

Just the two small questions

2021-04-11 13:25 UTC, oliverbarnes commented on app/overrides/commands/decidim/proposals/unvote_proposal.rb
> +        broadcast(:ok)
Would you pls elaborate on this change here?

2021-04-11 13:25 UTC, oliverbarnes commented on app/overrides/commands/decidim/proposals/vote_proposal.rb
> -        broadcast(:ok, vote)
Same - I'd like to understand where it was used in the broadcast consumer, and what changed that we don't need it anymore

2021-04-11 16:24 UTC, davefrey commented on app/overrides/commands/decidim/proposals/unvote_proposal.rb
> +        broadcast(:ok)
Yes, it's not used, and I was finding it confusing because the caller (the controller) already has a `@proposal` attribute that immediately gets refreshed anyway. See: https://github.com/liquidvotingio/decidim-module-liquidvoting/blob/850034b9c04831b913c153ad601a836bddaf231a/app/overrides/controllers/decidim/proposals/proposal_votes_controller.rb#L18-L20

Subscribers to a broadcast can use a returned value, but it's referenced in a block parameter, like (from `wisper` docs):
```ruby 
on(:cancel_order_successful) { |order_id| ... }
```
Possibly the controller is doing something implicitly with the return value, but in any case it's confusing to me: `proposal` in the controller is the same thing, and the first thing it does is refresh from the database.

Possibly something else in the Decidim codebase is subscribing to this event? I didn't find anything searching on the command names, I'd think they'd need to register by name?

Combined with the `VoteProposal` case, see below, I thought it just simpler to take them out, but we can also defensively leave them in, wdyt?

2021-04-11 16:24 UTC, davefrey commented on app/overrides/commands/decidim/proposals/vote_proposal.rb
> -        broadcast(:ok, vote)
This case is like unvote above, except more confusing: the `vote` here is a built-not-saved `ProposalVote`, a model we're not using. And, the controller never captures the return value or uses it, not that I can see.

Again I'm open to leaving them in defensively...it was a cleanup impulse I had.

2021-04-12 15:49 UTC, oliverbarnes commented on app/overrides/commands/decidim/proposals/unvote_proposal.rb
> +        broadcast(:ok)
Let's keep it, that makes sense. I had a look, and couldn't find where it could possibly be used either.

2021-04-12 15:49 UTC, oliverbarnes approved these changes

2021-04-12 15:49 UTC, merged